### ISSUE TITLE
GraphQL Error for each of the graphic options

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1001]
When dispalying the [Cube](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!swissprtronlytrucatedpq1-v3owjpbplmw/metadata) in [Visualize](https://int.visualize.admin.ch/en/create/eS3J_kjbPFd2?dataSource=Int). For each of the graphic options there will be an error message dispalyed as follows:
![graphql error](https://user-images.githubusercontent.com/111350367/226551303-1dedab15-8597-490e-b45d-699de02b5ae9.PNG)
There is no error or warnings in Cube Creator.

To reproduce, just follow the the Visualize link above.
Happens in both Edge and Firefox browsers

**Comment by sosiology** [comment]
Hi @tboeni thank you for your note. The link you shared takes me to the data set overview page, could you specify the name of the data set you are referring to?

**Comment by tboeni** [comment]
@sosiology Hi, sure the Cube is called SwissPRTROnlyTruncated_PQ_1 in Cube Creator not sure if this [link](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!swissprtronlytrucatedpq1-v3owjpbplmw/csv-mapping) is more helpful, or do you need the csv file which has been used for integration?

**Comment by sosiology** [comment]
Hi @tboeni 
Thank you very much. I think I was able to find the data set you are referring to and reproduce the error (see image below)
In future when taking screenshots, it is always helpful to include the data set in the screenshot (see image below), this helps us reproduce the  error on our side. Thanks in advance!

![image](https://user-images.githubusercontent.com/29289679/226709685-6daae777-726c-4017-906c-e40c876e1798.png)

**Comment by FabianCretton** [comment]
In the context of this possible "bug", Thomas Bettler suspects that Visualize can not handle a nominal dimension that is a string.
Which is, in his opinion, ok for the Cube schema, but not ok for Visualize.

A clarification about this would be great, thanks @ptbrowne or anyone.

**Comment by bprusinowski** [comment]
Hi, it seems that the error is related to some of the dimensions having a `langString` type. We have an explicit warning in the code that in such case, filtering won't work – it seems that Visualize hasn't been able to handle such dimensions for a long time (the code is over two years old).

While I am not exactly sure why this is the case, I wonder if the string dimensions should be formatted in a different way, like having localized `schema:name` instead of using the data type of `langString`? At least I think that's the case in other cubes, @FabianCretton was this the way you structured your cubes when it comes to localized strings?

**Comment by FabianCretton** [comment]
A few questions to better understand:
@tboeni What is this identifier ??
![image](https://user-images.githubusercontent.com/6167669/230084099-d5424cdf-acee-48e5-81d7-2763870826ab.png)
Are you sure all those fields are needed to identify one observation, and could the cause problems when generating a URL ?

@tboeni When I open the cube, The Cube Designer displays nothing and turns undefinitely: could this be an error because of my question here above ? Isn't it normal that Visualize can not load the data if the Cube Designer can not either ?

@bprusinowski I do not really understand your question about langString, I think we use strings with language tag very often (with schema:name but any other property), no ?

**Comment by bprusinowski** [comment]
Hi @FabianCretton, thanks for your answer! I think here the difference is that in other, working cubes, localised strings are inside a named node, like here:

<img width="1428" alt="Screenshot 2023-04-05 at 16 40 59" src="https://user-images.githubusercontent.com/52032047/230115898-fd4b482a-7dc6-4890-9b0c-9a4d4f41346b.png">

however inside the cube of @tboeni, it seems to be done via langString literal directly, I think this is the case of Visualize crashing.

<img width="1427" alt="Screenshot 2023-04-05 at 16 41 28" src="https://user-images.githubusercontent.com/52032047/230116031-82817c0e-630c-4e1b-99e0-227311b8c20d.png">

**Comment by FabianCretton** [comment]
@bprusinowski well, this is all perfectly fine RDF to me, so I do not understand why there should be a limitation here.
Was it a decision with Zazuko, and, if so, is it documented somewhere (in the Cube ontology or the Cube Creator User Guide) ?

But on second thought, the Cube Creator allows to have a language tag when defining the CSV mapping, so I think it is rather a "wrong assumption" in visualize, no ?

**Comment by FabianCretton** [comment]
@bprusinowski  and @tboeni 
I come back with some news, as I did create a[ copy of the cube](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!swissprtronlytrucatedpq1fab-jojrrkrdobd/csv-mapping), correcting what seemed strange to me.

My cube displays now fine in Visualize - cube name "Swissprtr Abfall TEST FAB".
@bprusinowski  I did not change anything about the langSring, so Visualize is fine with that, which is good new :-)

@tboeni, Here are the things I corrected in the cube, I think we can clairify this if it is not clear for you:
- The cube's identifier was strange, with all fields. Which would lead to very long URLs, I do not eve know what can happen in this case. I understand why you did that (the redundant lines with only the 'Wert' that is different), but it is not a good way to solve that. For my test, I did simply add a IDFake column with a unique number for each line
- In the Cube Designer, you defined 2 'Key dimensions', BetriebsID+Jahr, which are not creating a unique identifier
- In the Cube Designer, some dimensions had no name, I do not know how visualize could handle that ? (@bprusinowski )

**Comment by bprusinowski** [comment]
Thanks a lot for your support @FabianCretton! 💯

At first glance it looked that there was something wrong with `langStrings`, but I am glad that it turned out to not be a problem. I am still not sure why we have [such logic](https://github.com/visualize-admin/visualization-tool/blob/e03a61fea325a94656107d8e5b6c782ba5784129/app/rdf/queries.ts#L644-L648) in the app, @ptbrowne does it ring a bell?
